data:
  #global_batch_size: 4
  global_batch_size: 32
  batch_size: 4
  #batch_size: 128
  rl_batch_size: 16
  color_jitter_strength: 0.0
  crop_scale:
  - 0.98
  - 1.0
  crop_size: 224
  image_folder: imagenet_full_size/061417/
  num_workers: 10
  pin_mem: true
  root_path: $replace_this_with_absolute_path_to_your_datasets_directory
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
logging:
  folder: /persistence/world_models/
  dream_folder: /persistence/dreams/
  agent_folder: /persistence/agents/
  ownership_folder: /persistence
  write_tag: jepa
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 14
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: true
  #model_name: vit_micro
  model_name: vit_tiny
  agent_model_name: vit_tiny
  #model_name: vit_huge
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  #use_bfloat16: false
  use_bfloat16: true
optimization:
  ema:
  - 0.996
  - 1.0
  epochs: 100
  #epochs: 1000
  rl_epochs: 300
  #final_lr: 1.0e-07
  final_lr: 1.0e-06
  #final_weight_decay: 0.04
  final_weight_decay: 0.4
  ipe_scale: 1.0
  #lr: 0.00001
  lr: 0.0001
  start_lr: 0.000002
  warmup: 5
  #warmup: 10
  weight_decay: 0.04
  TAU: 0.005
  rl_warmup: 10
plateau:
  patience: 10
  #threshold: 1.0
  threshold: 0.1
  rl_patience: 10
  rl_threshold: 0.0001
memory:
  models: 1
  memory_models: 1
  dreams: 10
  rl_models: 1
dreamer:
  number_of_dreams: 20
  dream_length: 10
action:
  short:
    left:
    - -0.1
    - 0.0
    - 0.0
    right:
    - 0.1
    - 0.0
    - 0.0
    left_up:
    - -0.1
    - 0.1
    - 0.0
    right_up:
    - 0.1
    - 0.1
    - 0.0
    left_down:
    - -0.1
    - -0.1
    - 0.0
    right_down:
    - 0.1
    - -0.1
    - 0.0
    up:
    - 0.0
    - 0.1
    - 0.0
    down:
    - 0.0
    - -0.1
    - 0.0
    zoom_in:
    - 0.0
    - 0.0
    - 0.1
    zoom_out:
    - 0.0
    - 0.0
    - -0.1
  long:
    left:
    - -1.0
    - 0.0
    - 0.0
    right:
    - 1.0
    - 0.0
    - 0.0
    up:
    - 0.0
    - 1.0
    - 0.0
    down:
    - 0.0
    - -1.0
    - 0.0
    zoom_in:
    - 0.0
    - 0.0
    - 0.2
    zoom_out:
    - 0.0
    - 0.0
    - -0.2
